const STATUS_BY_CODE: Readonly<Record<string, number>> = {
  INVALID_AMOUNT: 400,
  INVALID_INPUT: 400,
  INVALID_JSON: 400,
  IDEMPOTENCY_KEY_REQUIRED: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  IDEMPOTENCY_IN_PROGRESS: 409,
  IDEMPOTENCY_KEY_REUSED: 409,
  PAYMENT_METHOD_REQUIRED: 409,
  INSUFFICIENT_CREDIT: 409,
  ALREADY_PAID: 409,
  CREDIT_UPDATE_FAILED: 500,
  PURCHASE_LOAD_FAILED: 500,
};

export function statusForCode(code: string): number {
  return STATUS_BY_CODE[code] ?? 500;
}
